### PR TITLE
fallback add when smoothquant

### PR DESCRIPTION
**Pull request by xin3he**
## Type of Change

enhancement

## Description

fallback add when smoothquant

## Expected Behavior & Potential Risk

add is fallbacked when smoothquant

## How has this PR been tested?

local test UT and checked the stats table

## Dependency Change?

N/A

### CODE REVIEW

**Review by hshen14 — APPROVED** [review]

**Comment by changwangss** [comment]
I remember fallback add will cause large latency, is it right? @PenghuiCheng
if it is true, please remove "t5" out. @xin3he

**Comment by hshen14** [comment]
> I remember fallback add will cause large latency for t5 and flan-t5, is it right? @PenghuiCheng if it is true, please remove "t5" out. @xin3he

@xin3he , by default, SmoothQuant will make Add FP32. Is it still possible to make Add INT8, if users specify in config through op-type? We should have such flexibility.

**Comment by xin3he** [comment]
> ant will make Add FP32.

In you description, it's a fallback strategy which has been refused by @mengniwang95  and @yiliu30

**Comment by xin3he** [comment]
Make user do the fallback add is still be best solution now.

**Comment by PenghuiCheng** [comment]
t5, flan-t5 performance:
fallback "add", int8 model slower than fp32 about 4~5x
no fallback "add, int8 model faster than fp32 model about 1.2x.

In t5 and flan-t5 , there are many add ops.

**Comment by hshen14** [comment]
Offline discussed with Yi, Xin, and Penghui. Yi will raise a new PR through the enhancement in strategy. Close it for now. Feel free to re-open if needed.

**Pull request closed without merging**
