### PR TITLE
Fix mix precision

### PR DESCRIPTION
**Pull request by mengniwang95**
## Type of Change

bug fix

## Description

Fix mix precision

### CODE REVIEW

**Comment by mengniwang95** [comment]
> please also fix in https://github.com/intel/neural-compressor/blob/mengni/mix/docs/source/quantization_mixed_precision.md#turn-off-auto-mixed-precision-during-quantization

I will add ORT part and @changwangss @lvliang-intel please check PT/TF parts

**Review by ftian1 — APPROVED** [review]

**Pull request merged**
