### PR TITLE
Refine docstring for newAPI, algorithm, and contrib

### PR DESCRIPTION
**Pull request by XuhuiRen**
Signed-off-by: XuhuiRen <xuhui.ren@intel.com>

## Docstring
Docstring for newAPI, contrib, and algorithm.

## Description
Add docstring for the document and add some function description.

detail description 
JIRA ticket: https://jira.devtools.intel.com/secure/RapidBoard.jspa?rapidView=32982&projectKey=ILITV&view=detail&selectedIssue=ILITV-2573&quickFilter=130297

### CODE REVIEW

**Review by WenjiaoYue — COMMENTED** [review]
Wrong path added

**Comment by XuhuiRen** [comment]
> Wrong path added

Done.

**Review by WenjiaoYue — APPROVED** [review]

**Pull request merged**
