### PR TITLE
Update onnx image_classification example

### PR DESCRIPTION
**Pull request by mengniwang95**
## Type of Change

example update

## Description

detail description 
JIRA ticket: 

[ILITV-2721](https://jira.devtools.intel.com/browse/ILITV-2721)

## Expected Behavior & Potential Risk

pre-ci and extension test pass

## How has this PR been tested?

extension test

model list: ultraface,emotion_ferplus,arcface,squeezenet_qdq,unet,resnet50_v1_5,mobilenet_v2,vgg16,resnet50-v1-12,resnet_v1_5_mlperf,mobilenet_v3_mlperf,vgg16_model_zoo,shufflenet-v2-12,googlenet-12,caffenet,alexnet,zfnet,inception_v1,efficientnet,mobilenetv2-12,mnist,densenet,resnet50_v1_5_qdq,mobilenet_v2_qdq,alexnet_qdq,caffenet_qdq,googlenet-12_qdq,zfnet_qdq,inception_v1_qdq,resnet50-v1-12_qdq,resnet_v1_5_mlperf_qdq,vgg16_qdq,vgg16_model_zoo_qdq,mobilenet_v3_mlperf_qdq,efficientnet_qdq,mobilenetv2-12_qdq,shufflenet-v2-12_qdq

## Dependency Change?

no

### CODE REVIEW

**Comment by mengniwang95** [comment]
https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4436/

**Comment by mengniwang95** [comment]
> https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4436/

https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4438/

**Comment by mengniwang95** [comment]
> 

https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4440/

**Comment by mengniwang95** [comment]
> > 
> 
> https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4440/

https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4456/

**Comment by mengniwang95** [comment]
> > > 
> > 
> > 
> > https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4440/
> 
> https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4456/

https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4474/

**Comment by mengniwang95** [comment]
> > > > 
> > > 
> > > 
> > > https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4440/
> > 
> > 
> > https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4456/
> 
> https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4474/

https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4483/

**Comment by mengniwang95** [comment]
> > > > > 
> > > > 
> > > > 
> > > > https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4440/
> > > 
> > > 
> > > https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4456/
> > 
> > 
> > https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4474/
> 
> https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4483/

https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4496/

**Comment by mengniwang95** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4440/
> > > > 
> > > > 
> > > > https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4456/
> > > 
> > > 
> > > https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4474/
> > 
> > 
> > https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4483/
> 
> https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4496/

https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4505/

**Comment by mengniwang95** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4440/
> > > > > 
> > > > > 
> > > > > https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4456/
> > > > 
> > > > 
> > > > https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4474/
> > > 
> > > 
> > > https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4483/
> > 
> > 
> > https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4496/
> 
> https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4505/

https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4542/

**Comment by mengniwang95** [comment]
https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4570/

**Comment by mengniwang95** [comment]
> https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4570/

https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4573/

**Comment by mengniwang95** [comment]
> > https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4570/
> 
> https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4573/

https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4576/

**Comment by mengniwang95** [comment]
https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4596/

**Comment by mengniwang95** [comment]
> https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4596/

https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4602/

**Comment by mengniwang95** [comment]
> > https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4596/
> 
> https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4602/

https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4611/

**Comment by mengniwang95** [comment]
> > > https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4596/
> > 
> > 
> > https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4602/
> 
> https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4611/

https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4625/

**Review by yuwenzho — APPROVED** [review]

**Comment by mengniwang95** [comment]
https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4662/

**Comment by mengniwang95** [comment]
https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4680/

**Comment by mengniwang95** [comment]
mobilenet_v2: different sampling_size, no opwise setting
vgg16: different sampling_size, no opwise setting
resnet50-v1-12: different sampling_size
mobilenet_v3_mlperf: different sampling_size
vgg16_model_zoo: different sampling_size
shufflenet-v2-12: different sampling_size
densenet: no opwise setting
resnet50_v1_5: different sampling_size

https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4687/

**Comment by mengniwang95** [comment]
https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4693/

**Comment by mengniwang95** [comment]
unet https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4694/

**Comment by mengniwang95** [comment]
> unet https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4694/

https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4695/

**Comment by mengniwang95** [comment]
> > unet https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4694/
> 
> https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4695/

https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4700/

**Pull request merged**
