### PR TITLE
remove synchronize for `pack_unpack_tensor_with_numpy`

### PR DESCRIPTION
**Pull request by Kaihui-intel**
## Type of Change

feature or bug fix or documentation or validation or others  
API changed or not

## Description

detail description

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Comment by xin3he** [comment]
@Kaihui-intel  let's wait till the Habana software 1.19.0 is merged back.

**Comment by thuang6** [comment]
could you give more background on this PR? why it is related to 1.19? is it expected to be cherry-picked to 1.19 release branch in INC fork?

**Comment by Kaihui-intel** [comment]
This PR is related to version 1.19 because it addresses a performance optimization related to unnecessary synchronization. The `synchronize` operation impacts the time spent on **unpacking** tensors on the HPU, and the `unpack_tensor_with_numpy` function, which only occurs on the CPU, does not require this synchronization. Therefore, the `synchronize` call is redundant and can be removed to improve efficiency.
As for the cherry-pick, it needs to be answered by @xin3he

**Comment by xin3he** [comment]
@thuang6  it's related with AutoRound PR and has conflict with it. so we should not merge this PR and wait util the AutoRound PR is cherry-picked back.
https://github.com/habana-internal/neural-compressor-fork/pull/25

**Pull request merged**
