### PR TITLE
enhance benchmark

### PR DESCRIPTION
**Pull request by xin3he**
## Type of Change

image

## Description

JIRA ticket: [NLPTOOLKIU-445](https://jira.devtools.intel.com/browse/NLPTOOLKIU-445)

### CODE REVIEW

**Comment by PenghuiCheng** [comment]
Can we modify the benchmark UT with new API?

**Review by PenghuiCheng — APPROVED** [review]

**Comment by chensuyue** [comment]
[extension test](https://inteltf-jenk.sh.intel.com/view/lpot-validation/job/intel-lpot-validation-top-mr-extension/4633/)

**Comment by xin3he** [comment]
> Can we modify the benchmark UT with new API?

not in this PR

**Pull request merged**
