### PR TITLE
Update DyNAS-T Interface

### PR DESCRIPTION
**Pull request by macsz**
# Update DyNAS-T interface to use the released PyPI version.

This PR removes all DyNAS-T code that resided within the Neural Compressor and modifies the `DyNAS` class interface to use the open-sourced version of the DyNAS-T (https://pypi.org/project/dynast/).

As the `DyNAS` class interface remains (on the top-level) unchanged, the expected behavior is unchanged and any code using the `DyNAS` class should remain operational without requiring any new changes.

The code has been tested both with unit tests and functional tests in the end-to-end scenario. As some of the code has been removed from this repo, certain tests have been removed as well, as these were already covered by the tests available in the https://github.com/IntelLabs/DyNAS-T/

```python
config = NASConfig(approach='dynas', search_algorithm='nsga2')

config.dynas.supernet = SUPERNET
config.seed = 51
config.nas.search.seed = 61

config.dynas.metrics = ['accuracy_top1', 'macs']

config.dynas.population = 50
config.dynas.num_evals = 250
config.dynas.results_csv_path = 'res_ofa.csv'
config.dynas.batch_size = 128
config.dynas.dataset_path = '/datasets/imagenet'
config.dynas.distributed = False

agent = NAS(config)
results = agent.search()
```

This PR also removes all previously listed dependencies from test requirements and replaced them with just one (`dynast`).

## New features

This PR also includes two new features:

* support for distributed search with `MPI`/`torchrun`.
* new search space - BERT Base finetuned on the SST-2 dataset.

Please refer to included notebook examples located in `examples/notebook/dynas/` for more details on how to use new features.

Signed-off-by: Maciej Szankin <maciej.szankin@intel.com>

### CODE REVIEW

**Comment by chensuyue** [comment]
> ## Type of Change
> feature or bug fix or documentation or validation or others API changed or not
> 
> ## Description
> detail description JIRA ticket: xxx
> 
> ## Expected Behavior & Potential Risk
> the expected behavior that triggered by this PR
> 
> ## How has this PR been tested?
> how to reproduce the test (including hardware information)
> 
> ## Dependency Change?
> any library dependency introduced or removed

Please update the description with correct information.

**Comment by macsz** [comment]
> > ## Type of Change
> > feature or bug fix or documentation or validation or others API changed or not
> > ## Description
> > detail description JIRA ticket: xxx
> > ## Expected Behavior & Potential Risk
> > the expected behavior that triggered by this PR
> > ## How has this PR been tested?
> > how to reproduce the test (including hardware information)
> > ## Dependency Change?
> > any library dependency introduced or removed
> 
> Please update the description with correct information.

Done. Was testing if changing the PR to "ready for review" would trigger CI. Any ideas why it's all pending (it's been pending for 16+ hours)? Are there no CI checks required now?

**Comment by macsz** [comment]
There is no dep in `dynas-t` that requires `protobuf` yet CI still fails on it. Reverted your change @chensuyue to see if this affected the tests somehow.

**Review by ftian1 — APPROVED** [review]

**Review by XinyuYe-Intel — APPROVED** [review]

**Pull request merged**
