### PR TITLE
Add operators statistics for IPEX backend

### PR DESCRIPTION
**Pull request by PenghuiCheng**
## Type of Change

add new feature
API changed

## Description

Add operators statistics for IPEX backend

## Expected Behavior & Potential Risk

Statistics int8 ops for IPEX backend.

## How has this PR been tested?

Local tested.

### CODE REVIEW

**Review by changwangss — APPROVED** [review]

**Comment by changwangss** [comment]
bf16 op type didn't be counted due to use torch.amp.autocast(), will be improve later with another PR when JIT model canbe parsed .

**Comment by chensuyue** [comment]
Please remove `no cover` for `class PyTorch_IPEXAdaptor(TemplateAdaptor):` and add ut for the new code.

**Comment by PenghuiCheng** [comment]
@chensuyue , This PR is ready.

**Comment by chensuyue** [comment]
Please add UT.

**Review by xin3he — APPROVED** [review]

**Pull request merged**
