### PR TITLE
fix pt notebook benchmark

### PR DESCRIPTION
**Pull request by violetch24**
## Type of Change
fix pt notebook benchmark

### CODE REVIEW

**Comment by eduand-alvarez** [comment]
Hey there, these updates resolve some but not all issues. You can't load the model without a config file. Should we be using the optimum intel tooling to load this?

**Comment by eduand-alvarez** [comment]
How do we load inc models that don't have config.json ?

**Comment by violetch24** [comment]
> How do we load inc models that don't have config.json ?

If `save_results` path doesn't contain model configs, please use the following command instead:
```py
if args.input_model:
    from neural_compressor.utils.pytorch import load
    model = load(args.input_model, model, dataloader=eval_dataloader)
```
Modifications have been made in the latest commit.

**Comment by eduand-alvarez** [comment]
Correct, with that change, the sample notebook runs as expected.

**Review by chensuyue — APPROVED** [review]

**Pull request merged**
