### PR TITLE
Remove 1x

### PR DESCRIPTION
**Pull request by yiliu30**
### Remove 1.x related code

Some folders and files include both 1.x and 2.x UTs. I've removed the 1.x UTs if they import something from `experimental` or `conf`. Please help double-check. Thanks!

- [x] ORT @mengniwang95 @yuwenzho 
- [x] Torch @xin3he @PenghuiCheng 
- [x] TF @zehao-intel 
- [x] Pruning @wenhuach21 @yintong-lu 
- [x] NAS, distillation @XinyuYe-Intel 

---------------------- 
### Track some changes:
@chensuyue @XuehaoSun , need your help to update the CI for the below changes:
- [x] [Model-Test (Run PyTorch Model resnet18)](https://dev.azure.com/lpot-inc/b7121868-d73a-4794-90c1-23135f974d09/_build/results?buildId=31619&view=logs&jobId=e3333e26-4334-5d5e-a7bd-ee7471860e42) is 1.x example. https://github.com/intel/neural-compressor/pull/1898
- [x] ~~All `tfnewapi` UTs are based on the 1.x, should we remove the CI for it?~~
- [x] All nas-relaed UTs have been removed, need to update the `base_api` CI.  https://github.com/intel/neural-compressor/pull/1896

@changwangss , need your help to clean some code on itrex side. 
- [x] Replace ` from neural_compressor.conf.dotdict import DotDict` with `from neural_compressor.utils.utility import DotDict` https://github.com/intel/intel-extension-for-transformers/pull/1645
- [x] Update `from neural_compressor.experimental import common` https://github.com/intel/intel-extension-for-transformers/pull/1645
----------------
optimum-intel @changwangss 
- [x]  update `from neural_compressor.experimental.export import torch_to_int8_onnx`, https://github.com/huggingface/optimum-intel/pull/777 updated it, but ITREX CI uses `optimum-intel==1.16.1`. https://github.com/intel/intel-extension-for-transformers/pull/1651
- [x] Update `optimum/intel/neural_compressor/trainer.py`'s `from neural_compressor.conf.pythonic_config import _BaseQuantizationConfig`. `python test_modeling.py --verbose` failed.  https://github.com/huggingface/optimum-intel/pull/801  https://github.com/intel/intel-extension-for-transformers/pull/1654

----------
- [ ] Delete docs by separate PRs. @yiliu30  https://github.com/intel/neural-compressor/pull/1900
## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Comment by yiliu30** [comment]
### Track some changes:
- [Model-Test (Run PyTorch Model resnet18)](https://dev.azure.com/lpot-inc/b7121868-d73a-4794-90c1-23135f974d09/_build/results?buildId=31619&view=logs&jobId=e3333e26-4334-5d5e-a7bd-ee7471860e42) is 1.x example

**Review by zehao-intel — APPROVED** [review]

**Review by yuwenzho — APPROVED** [review]
ORT part looks good to me

**Comment by mengniwang95** [comment]
please also delete related doc

**Comment by yiliu30** [comment]
> please also delete related doc

Sure, will delete docs by separate PRs.

**Review by mengniwang95 — APPROVED** [review]

**Comment by yiliu30** [comment]
```bash
compare coverage
PR lines coverage: 31017/41008 (75.636%)
PR branches coverage: 10786/16871 (63.932%)
BASE lines coverage: 44335/52654 (84.201%)
BASE branches coverage: 15819/21486 (73.625%)
clear upload path
Unit Test failed with lines coverage decrease -8.565%
Unit Test failed with branches coverage decrease -9.693%
compare coverage to give detail info

```

**Review by XinyuYe-Intel — APPROVED** [review]

**Review by PenghuiCheng — APPROVED** [review]

**Review by chensuyue — APPROVED** [review]

**Comment by wenhuach21** [comment]
@n1ck-guo  Please help review the pruning code. I have read through it, but I am not very familiar with it anymore.

**Review by n1ck-guo — APPROVED** [review]

**Pull request merged**
