### PR TITLE
Support per-channel MatMul quantization

### PR DESCRIPTION
**Pull request by Spycsh**
## Type of Change

feature

## Description

support per-channel MatMul quantization

## Expected Behavior & Potential Risk

MatMul can be quantized channel-wise & We can have per-channel minmax of MatMul on the quantized graph

## How has this PR been tested?

on latest spr, run distilbert_base with specifying `op_type_dict={'matmul':{'weight':{'granularity':['per_channel']}}}`

## Dependency Change?

None

### CODE REVIEW

**Comment by lvliang-intel** [comment]
extension test: https://inteltf-jenk.sh.intel.com/view/lpot-oob/job/intel-lpot-validation-top-extension-TFnewAPI/367/

**Comment by Spycsh** [comment]
`op_type_dict={'matmul':{'weight':{'granularity':['per_channel']}}}`
This matmul should be lower-cased

**Comment by Spycsh** [comment]
for debug

https://inteltf-jenk.sh.intel.com/view/lpot-oob/job/intel-lpot-validation-top-extension-TFnewAPI/369/

**Comment by Spycsh** [comment]
per-tensor

https://inteltf-jenk.sh.intel.com/view/lpot-oob/job/intel-lpot-validation-top-extension-TFnewAPI/370/

**Comment by Spycsh** [comment]
seems the latest spr based version is not included in the yaml...

**Comment by Spycsh** [comment]
per-tensor: https://inteltf-jenk.sh.intel.com/view/lpot-oob/job/intel-lpot-validation-top-extension-TFnewAPI/371/

**Comment by Spycsh** [comment]
Now the new spr version is included. We are going to compare per-channel acc vs. per-tensor acc with two tests

1) test for per-tensor

if succeed, then
2) for multiple models which are not as default using per-channel, we have to remove per-tensor in yaml to test per-channel

**Comment by Spycsh** [comment]
Hi @chensuyue , @lvliang-intel , could you review this? Per-channel MatMul is set as an optional parameter in PTQConfig, and the README in bert_mrpc explains how to use it.

**Review by lvliang-intel — APPROVED** [review]

**Review by chensuyue — APPROVED** [review]

**Pull request merged**
