### PR TITLE
Enhance SmoothQuant tuning structure.

### PR DESCRIPTION
**Pull request by xin3he**
## Type of Change

feature

## Description
New implement can avoid duplicated calibration of SmoothQuant, and especially for IPEX, it avoids a deepcopy of fp32 model for SmoothQuant, we can apply scale to the prepared model directly.
```
alpha = [0.5, 0.55, ...]

After: 
1. FP32 smoothquant -> (i_max, w_max), alpha-> scale
2. query capability ->prepared model

for a in alpha:
    3. quantize
        (i_max, w_max) +a -> scale
        torch.mul(scale)
        scale -> json
        convert 
         eval_func

Before(abandon):
1.query capability ->prepared model
for a in alpha:
    2. FP32 smoothquant -> (i_max, w_max), alpha-> scale
    3.  quantize
        prepare
        convert 
         eval_func
```

## Expected Behavior & Potential Risk

UT pass

## How has this PR been tested?

local test

## Dependency Change?

N/A

### CODE REVIEW

**Comment by hshen14** [comment]
Good initiative @xin3he . For the new one (this PR), shall we expose below APIs (no loop) to end users? We can provide both high-level APIs for beginners and low-level APIs for advanced users. @wenhuach21 requested this feature before.

1. FP32 smoothquant -> (i_max, w_max), alpha-> scale
2. query capability ->prepared model
3. quantize ...

**Comment by xin3he** [comment]
> Good initiative @xin3he . For the new one (this PR), shall we expose below APIs (no loop) to end users? We can provide both high-level APIs for beginners and low-level APIs for advanced users. @wenhuach21 requested this feature before.
> 
> 1. FP32 smoothquant -> (i_max, w_max), alpha-> scale
> 2. query capability ->prepared model
> 3. quantize ...

It's not easy, The most important thing is pass the infos, such as SQ scale and FP32 add, to ipex_config.json. Right now, updating fallback info and updating SQ info are implemented seperately in two function which need to be merged and these two rely on a specific tune_cfg from strategy. We need to plan a better structure on updating ipex_config.json, which requires some resource to design.

**Comment by hshen14** [comment]
> > Good initiative @xin3he . For the new one (this PR), shall we expose below APIs (no loop) to end users? We can provide both high-level APIs for beginners and low-level APIs for advanced users. @wenhuach21 requested this feature before.
> > 
> > 1. FP32 smoothquant -> (i_max, w_max), alpha-> scale
> > 2. query capability ->prepared model
> > 3. quantize ...
> 
> It's not easy, the most important thing is how to pass the infos, such as SQ scale and FP32 add, to ipex_config.json. Right now, updating fallback info and updating SQ info are implemented seperately in two function which need to be merged and these two rely on a specific tune_cfg from strategy. We need to plan a better structure on updating ipex_config.json, which requires some resource to design.

Ok to go with this first.

**Comment by yiliu30** [comment]
UT test: python test/algorithm/test_smooth_quant.py TestTuneSqAlpha.test_tune_sq_alpha

**Review by hshen14 — APPROVED** [review]

**Review by wenhuach21 — APPROVED** [review]

**Review by PenghuiCheng — APPROVED** [review]

**Pull request merged**
