### PR TITLE
Unify the `logger` usage

### PR DESCRIPTION
**Pull request by yiliu30**
## Type of Change

API changed or not:  None

## Description

```python
# Recommend usage
from neural_compressor.common import logger
logger.info("Log info: %s", log_str)

from neural_compressor.common import Logger
from neural_compressor.common.utils import Logger
logger = Logger().get_logger()
logger.info("Log info: %s", log_str)
```

## How has this PR been tested?
Pre-CI

## Dependency Change?
None

### CODE REVIEW

**Comment by yiliu30** [comment]
Hi @chensuyue, the UT coverage report shows that all PR and base files have the same branch and Miss, yet the coverage has fallen nonetheless. Am I missing something?

image

**Comment by chensuyue** [comment]
> Hi @chensuyue, the UT coverage report shows that all PR and base files have the same branch and Miss, yet the coverage has fallen nonetheless. Am I missing something?
> 
> image

Coverage count should have some issues, I will check.

**Comment by chensuyue** [comment]
image
image
In this case, line/branch covered and overall item decrease the same number, so the ratio decreased, but the missed line didn't change. In most of other cases, new PR will increase the overall code lines and branch.

**Comment by yiliu30** [comment]
> image image In this case, the covered line/branch and overall item decrease the same number, so the ratio decreased, but the missed line didn't change. In most of other cases, new PR will increase the overall code lines and branch.

Nice catch, thanks.

**Pull request merged**
