### PR TITLE
add UT for distillation_for_quantization with gpu

### PR DESCRIPTION
**Pull request by XuhuiRen**
## Type of Change

add UT test for distillation_for_quantization with gpu

### CODE REVIEW

**Review by xin3he — APPROVED** [review]

**Comment by xin3he** [comment]
Please leave a message after testing on GPU.

**Comment by XuhuiRen** [comment]
> Please leave a message after testing on GPU.

ok

**Comment by PenghuiCheng** [comment]
Can we split the UT to test_oneshot.py and test_orchestration.py, test_oneshot.py is for 1.x API, and test_orchestration.py is for 2.x API.

**Comment by XuhuiRen** [comment]
> Please leave a message after testing on GPU.

Passed 

> Please leave a message after testing on GPU.

Success on mlp-dgx server

**Comment by XuhuiRen** [comment]
> Can we split the UT to test_oneshot.py and test_orchestration.py, test_oneshot.py is for 1.x API, and test_orchestration.py is for 2.x API.

done

**Pull request merged**
