### PR TITLE
Remove Dequantize Cast Optimizer MIN_FIRST limitation for spr-base

### PR DESCRIPTION
**Pull request by lvliang-intel**
## Type of Change

feature
API not changed

## Description

Dequantize with mode MIN_FIRST has already supported bf16 in spr-base. 
Remove the limitation to delete the redundant Cast ops.

## Expected Behavior & Potential Risk

Some models performance can be improved in spr-base since redundant Cast ops can be removed.

## How has this PR been tested?

Pre-CI and extension test for spr-base and stock tf.

## Dependency Change?

No.

### CODE REVIEW

**Comment by lvliang-intel** [comment]
Extension test for spr-base: https://inteltf-jenk.sh.intel.com/view/lpot-oob/job/intel-lpot-validation-top-extension-TFnewAPI/368/

**Comment by lvliang-intel** [comment]
Extension test for stock tf: https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/5050/

**Comment by chensuyue** [comment]
Please fix UT issue

**Comment by lvliang-intel** [comment]
extension test passed.  
https://inteltf-jenk.sh.intel.com/view/lpot-validation/job/intel-lpot-validation-top-extension-TFnewAPI/402/artifact/report.html

**Pull request merged**
