### PR TITLE
Add table-transformer-detection ONNXRT example

### PR DESCRIPTION
**Pull request by yuwenzho**
## Type of Change

example
API not change

## Description

Add table-transformer-detection ONNXRT example. https://github.com/microsoft/table-transformer

## How has this PR been tested?

CI test, extension test

## Dependency Change?

No

### CODE REVIEW

**Review by hshen14 — APPROVED** [review]

**Comment by chensuyue** [comment]
Does this PR pass the extension test?

**Comment by yuwenzho** [comment]
> Does this PR pass the extension test?

[extesnion test](https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/5371/) is still running

**Comment by yuwenzho** [comment]
> > Does this PR pass the extension test?
> 
> [extesnion test](https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/5371/) is still running

Extension test failed, I am fixing now

**Comment by yuwenzho** [comment]
table_tansformer_detection pass [extension test](https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/5382/artifact/report.html)
table_transformer_structure_recognition pass [extension test](https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/5383/artifact/report.html) (tune_only mode)

**Review by chensuyue — APPROVED** [review]

**Pull request merged**
