### PR TITLE
Refine PT2ONNX export

### PR DESCRIPTION
**Pull request by yuwenzho**
## Type of Change

feature 
API not changed

## Description

Refine PT2ONNX export

old PT2ONNX export workflow: 

- step 1: get quantized ops + scale & zp info from INT8 PT
- step 2: export FP32 PT to FP32 ONNX, then quantize to INT8 ONNX with quantized ops info collected in step1
- step 3: map scale & zp info collected in step1 to INT8 ONNX

new PT2ONNX export workflow:

- INT8 PT --> model wrapper (to unify model output) --> export to INT8 ONNX

## Expected Behavior & Potential Risk

pass extension test of export

## How has this PR been tested?

[extension test of export](https://inteltf-jenk.sh.intel.com/view/lpot-validation/job/inc-model-export-test-top-extension/)

## Dependency Change?

no

### CODE REVIEW

**Review by hshen14 — APPROVED** [review]
LGTM

**Comment by yuwenzho** [comment]
extension test of export: https://inteltf-jenk.sh.intel.com/view/lpot-validation/job/inc-model-export-test-top-extension/4/

**Pull request merged**
