### PR TITLE
Fix customer LSTM model quantization issues

### PR DESCRIPTION
**Pull request by lvliang-intel**
## Type of Change

bug fix
API not changed

## Description

detail description 
JIRA ticket: ILITV-2725

## Expected Behavior & Potential Risk

Customer models quantization issues can be fixed.

## How has this PR been tested?

Pre-CI and OOB extension test.

## Dependency Change?

No.

### CODE REVIEW

**Comment by chensuyue** [comment]
[extension test](https://inteltf-jenk.sh.intel.com/view/lpot-validation/job/intel-lpot-validation-top-mr-extension/4447/artifact/report.html)

**Comment by chensuyue** [comment]
Generate new [CI refer](https://dev.azure.com/lpot-inc/neural-compressor/_build/results?buildId=9401&view=results) due to the performance update.

**Comment by lvliang-intel** [comment]
extension test:
https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-extension-TFnewAPI/351/artifact/report.html
https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-extension-TFnewAPI/353/artifact/report.html

**Review by zehao-intel — APPROVED** [review]

**Pull request merged**
