### PR TITLE
add default value for recipes

### PR DESCRIPTION
**Pull request by mengniwang95**
## Type of Change

bug fix 

## Description

add default value for recipes

### CODE REVIEW

**Comment by chensuyue** [comment]
[extension test](https://inteltf-jenk.sh.intel.com/view/lpot-validation/job/intel-lpot-validation-top-mr-extension/4468/)

**Comment by mengniwang95** [comment]
https://inteltf-jenk.sh.intel.com/view/lpot-validation/job/intel-lpot-validation-top-mr-extension/4488/

**Comment by mengniwang95** [comment]
> https://inteltf-jenk.sh.intel.com/view/lpot-validation/job/intel-lpot-validation-top-mr-extension/4488/

https://inteltf-jenk.sh.intel.com/view/lpot-validation/job/intel-lpot-validation-top-mr-extension/4504/

**Pull request merged**
