### PR TITLE
Add docstring for WOQ&LayerWise

### PR DESCRIPTION
**Pull request by Kaihui-intel**
## Type of Change

documentation

## Description

detail description

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Comment by Kaihui-intel** [comment]
@yiliu30 Could you help add the hqq docstring?

**Comment by yiliu30** [comment]
> @yiliu30 Could you help add the hqq docstring?

Sure, will add it by a separate PR.

**Comment by yiliu30** [comment]
Please update the scan path.

https://github.com/intel/neural-compressor/blob/master/.azure-pipelines/scripts/codeScan/pydocstyle/scan_path.txt

**Comment by yiliu30** [comment]
> > @yiliu30 Could you help add the hqq docstring?
> 
> Sure, will add it by a separate PR.

Added docstring for hqq at https://github.com/intel/neural-compressor/pull/1937

**Review by xin3he — APPROVED** [review]

**Review by xin3he — APPROVED** [review]

**Review by yiliu30 — APPROVED** [review]
Please update the scan path before merging.

https://github.com/intel/neural-compressor/blob/master/.azure-pipelines/scripts/codeScan/pydocstyle/scan_path.txt

**Pull request merged**
