### PR TITLE
Enable Pruning New API for TF Adaptor

### PR DESCRIPTION
**Pull request by zehao-intel**
## Type of Change

feature
API not changed

## Description

Jira: [ILITV-2822](https://jira.devtools.intel.com/browse/ILITV-2822)

## Expected Behavior & Potential Risk

Enable Pruning New API for TF Adaptor

## How has this PR been tested?

Extension test

## Dependency Change?

No

### CODE REVIEW

**Comment by chensuyue** [comment]
@XuehaoSun please help to enable extension test for the TF pruning examples.

**Comment by zehao-intel** [comment]
Extension tests passed：
ViT: https://inteltf-jenk.sh.intel.com/job/inc-pruning-test/151/
ResnetV2: https://inteltf-jenk.sh.intel.com/job/inc-pruning-test-top/58/

**Review by YIYANGCAI — APPROVED** [review]

**Comment by chensuyue** [comment]
Need to fix the coverage regression.

**Comment by wenhuach21** [comment]
Please kindly add me to the reviewers if there are any significant changes of the pruning module in the future.

**Comment by zehao-intel** [comment]
> Please kindly add me to the reviewers if there are any significant changes of the pruning module in the future.

Sure.

**Pull request merged**
