### PR TITLE
Replace the np.bool with python built-in bool

### PR DESCRIPTION
**Pull request by ronggegu**
## Type of Change

bug fix

## Description

module 'numpy' has no attribute 'bool'

## Expected Behavior & Potential Risk

model test pass

## How has this PR been tested?

extension test

## Dependency Change?

no

### CODE REVIEW

**Comment by ronggegu** [comment]
extension test pass: https://inteltf-jenk.sh.intel.com/view/lpot-validation/job/intel-lpot-validation-top-mr-extension/4039

**Comment by ronggegu** [comment]
extension test pass https://inteltf-jenk.sh.intel.com/view/lpot-validation/job/intel-lpot-validation-top-mr-extension/4062/

**Comment by ronggegu** [comment]
test pass https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4066/

**Review by chensuyue — APPROVED** [review]

**Pull request merged**
