### PR TITLE
add deepcopy for SQ folding=True

### PR DESCRIPTION
**Pull request by changwangss**
## Type of Change

bug fix
root cause: when `folding=True` and `eval_func` doesn't provide, the SQ input is ipex prepared model, it used `aten::alias` wrap the op and cause the `linear` and `conv` not to be recognized.
improve: add the deepcopy for this condition, because `folding=False` also need `deepcopy`, so remove the ipex version limitation.

remaining:
there is a remaining curious issue in UT `python test_smooth_quant.py TestSqLinearOpFuse.test_sq_quant_ipex`, for actual models(such as bloom, llama), `tmp_model` and `model` should use the same address. But the previous ut pass, the reason shows `tmp_model=model` create 2 address for `tmp_model` and `model` when get_quantizable ops, I think may be due to the small size, please root cause @xin3he 

## Description

detail description

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Review by xin3he — APPROVED** [review]

**Comment by hshen14** [comment]
Why adding deepcopy back? @xin3he did you sort out with IPEX team to see whether one-time calibration/quantization is enough?

**Comment by xin3he** [comment]
> Why adding deepcopy back? @xin3he did you sort out with IPEX team to see whether one-time calibration/quantization is enough?

Yeah, we will raise JIRA to them.

**Review by hshen14 — APPROVED** [review]
LGTM

**Comment by xin3he** [comment]
The root cause of this issue is that when we use `inplace=True` in `ipex.prepare`, both model will get hooks and cause trace error while having different ids
In UT, the prepared model got hooks while the other one is pure.
I have raised this unexpected behavior to IPEX team internal. [internal link](https://jira.devtools.intel.com/browse/IPB-1767)

**Pull request merged**
