### PR TITLE
Update pruning sparsity frequency

### PR DESCRIPTION
**Pull request by echarlaix**
In this PR we update the desired sparsity at a given epoch, in order to prune at the end of the `start_epoch` and also add the ability to prune in one epoch (in case `start_epoch == end_epoch`)

### CODE REVIEW

**Comment by changwangss** [comment]
for example in origin code,
```
setting:
self.start_epoch=0,  self.end_epoch=3
---------------------------------------------------------------
when epoch=0, sparisity=self.inital_sparisity,
when epoch=1, sparisity=self.inital_sparisity+1/3*(self.target_sparsity - self.initial_sparsity)
when epoch=2, sparisity=self.inital_sparisity+2/3*(self.target_sparsity - self.initial_sparsity)
when epoch=3, sparisity=self.inital_sparisity+3/3*(self.target_sparsity - self.initial_sparsity)=self.target_sparsity
---------------------------------------------------------------
finally, when the `epoch=self.end_epoch`, sparisity reach the self.target_sparisity
```

**Review by XinyuYe-Intel — APPROVED** [review]

**Comment by PenghuiCheng** [comment]
test lpot

**Comment by PenghuiCheng** [comment]
> for example in origin code,
> 
> ```
> setting:
> self.start_epoch=0,  self.end_epoch=3
> ---------------------------------------------------------------
> when epoch=0, sparisity=self.inital_sparisity,
> when epoch=1, sparisity=self.inital_sparisity+1/3*(self.target_sparsity - self.initial_sparsity)
> when epoch=2, sparisity=self.inital_sparisity+2/3*(self.target_sparsity - self.initial_sparsity)
> when epoch=3, sparisity=self.inital_sparisity+3/3*(self.target_sparsity - self.initial_sparsity)=self.target_sparsity
> ---------------------------------------------------------------
> finally, when the `epoch=self.end_epoch`, sparisity reach the self.target_sparisity
> ```

So the PR "[Update pruning frequency to start at start_epoch](https://github.com/intel/neural-compressor/pull/89/commits/d275315bce744795aa6f7c493f05e424c5eb786c)" is not necessary, is it right?

**Review by XinyuYe-Intel — CHANGES_REQUESTED** [review]
'+1' in line 128&129 will cause sparsity do not equal self.initial_sparsity in start_epoch, maybe we should discuss it a little bit?

**Comment by changwangss** [comment]
Thanks for Ella's good idea.
finally, we agree with suggestion, and will remove internal repo to test and then merge it. 
Once the internal repo is merged, after the nightly test is successful, this repo will be synchronized with the internal repo.
If you don't have any other questions, I suggest that this pull request can be closed.

**Comment by hshen14** [comment]
Thanks for your contribution! The PR has been merged: ad227fc3fa93ff4340a41400e82462267e0b0ec2. Closing the PR now.

**Pull request closed without merging**
