### PR TITLE
support models that need to be loaded using cuda

### PR DESCRIPTION
**Pull request by guotuofeng**
## Type of Change

Mistral model need to be loaded using CUDAExeuctionProvider. But the existing model loading only use CPUExecutionProvider.

## Description

This PR just enable the CUDA EP support.

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Comment by yuwenzho** [comment]
Better to set `providers=onnxruntime.get_available_providers()`. CUDA EP may not be available on all devices.

**Comment by guotuofeng** [comment]
> onnxruntime.get_available_providers()

It seems the onnxruntime.get_available_providers() doesn't work.
1. if the appropriated CUDA dependencies is not ready, the following errors will be raised.
image
2. On another hand, I install the CPU onnxruntime, and try to create InferenceSession by get_available_providers. then the following errors is raise:
image

**Comment by guotuofeng** [comment]
> Better to set `providers=onnxruntime.get_available_providers()`. CUDA EP may not be available on all devices.

the default onnxruntime cpu version will have "AzureExecutionProvider" when invoking get_available_providers. Is that expected?

**Comment by yuwenzho** [comment]
Hi @guotuofeng, By default, ONNX Runtime always places input(s) and output(s) on CPU. All model should be able to run on CPU EP. 
We plan to support CUDA EP for WOQ in this PR #1490

**Comment by guotuofeng** [comment]
> Hi @guotuofeng, By default, ONNX Runtime always places input(s) and output(s) on CPU. All model should be able to run on CPU EP. We plan to support CUDA EP for WOQ in this PR #1490. We may not change code in `model.py` and `onnxrt.py`

So, should I close this PR since you guys will take care of it?

**Comment by yuwenzho** [comment]
Support of CUDA EP for WOQ and related optimization of EP providers will be maintained in #1490

**Pull request closed without merging**
