### PR TITLE
Update DyNAS interface

### PR DESCRIPTION
**Pull request by macsz**
Signed-off-by: Maciej Szankin <maciej.szankin@intel.com>

### CODE REVIEW

**Review by ftian1 — APPROVED** [review]

**Comment by ftian1** [comment]
thanks Maciej, yes, this is what we prefer. thanks for the quick update

**Comment by macsz** [comment]
We still have to work on the `NASConfig` class, as it currently does not have an option to pass Dynas/NASBase objects to it, but given the timeline I think we can work on it for 2.1.

```python
dynas_setting = Dynas(supernet='transformer_lt_wmt_en_de', metrics=..., population=..., ...)
config = NASConfig(approach='dynas', search_algorithm='nsga2', seed=42, setting=dynas_setting)
agent = NAS(config)
results = agent.search()
```

**Comment by ftian1** [comment]
> We still have to work on the `NASConfig` class, as it currently does not have an option to pass Dynas/NASBase objects to it, but given the timeline I think we can work on it for 2.1.
> 
> ```python
> dynas_setting = Dynas(supernet='transformer_lt_wmt_en_de', metrics=..., population=..., ...)
> config = NASConfig(approach='dynas', search_algorithm='nsga2', seed=42, setting=dynas_setting)
> agent = NAS(config)
> results = agent.search()
> ```

totally agree. thanks for your effort

**Comment by macsz** [comment]
As discussed with @ftian1 today this should be postponed to next release (or release after).

**Pull request closed without merging**
