### PR TITLE
Recommend installing `numba` and `tbb` for WoQ

### PR DESCRIPTION
**Pull request by yiliu30**
Fix https://github.com/intel/neural-compressor/issues/2031#issuecomment-2429698785

render version https://github.com/intel/neural-compressor/blob/numba_doc/docs/source/3x/PT_WeightOnlyQuant.md#get-started

### CODE REVIEW

**Review by Kaihui-intel — APPROVED** [review]

**Comment by xin3he** [comment]
Could we also simplify the log message?
image

**Comment by xin3he** [comment]
BTW, many colleagues complain with me about the tbb issue. 
How about using below logic:
try:
   if not check_numba_tbb():
       logger.warning("To accelerate packing, please install numba with `pip install numba tbb`")
except:
   logger.warning(“numba and tbb is installed but tbb is not correctly configured")
   logger.warning(“please follow xxx to configure it, here we use numpy instead")

**Comment by yiliu30** [comment]
> BTW, the tbb issue is not friendly. It will break progress during quantization. How about using below logic:
> 
> ```
> try:
>    if not is_numba_tbb_available():               # no package
>        logger.warning("To accelerate packing, please install numba with `pip install numba tbb`")
> except:                                                         # has package but installed incorrectly
>    logger.warning(“numba and tbb is installed but tbb is not correctly configured")
>    logger.warning(“please follow xxx to configure it, here we use numpy instead")
> ...                                                                  # has package and installed correctly
> ```
> 
> `is_numba_tbb_available` should both check installation and tbb configuration


Do you mean the program will crash if `tbb` isn’t configured correctly?

It’s not easy to summarize how to make `numba` and `tbb` work as expected in one sentence; maybe I could write a short note for it.

**Comment by xin3he** [comment]
Yes, It will cruch. BTW, I mean use link here.
`logger.warning(f“please follow {link} to configure it, here we use numpy instead")`

**Comment by yiliu30** [comment]
> Yes, It will cruch. BTW, I mean to use link here. we already have introduce about this issue in FAQ. `logger.warning(f“please follow {link} to configure it, here we use numpy instead")`

I see, I will enhance this check.

**Comment by yiliu30** [comment]
Enhanced the `TBB` check on https://github.com/intel/neural-compressor/pull/2068, close it.

**Pull request closed without merging**
