### PR TITLE
Optimize Windows multi-instance benchmark

### PR DESCRIPTION
**Pull request by Spycsh**
## Type of Change

bug fix

## Description

detail description 
JIRA ticket: [ILITV-2571](https://jira.devtools.intel.com/browse/ILITV-2571)

## Expected Behavior & Potential Risk

Any windows example can successfully run multi-instance
and also produce the log

## How has this PR been tested?

CI test

## Dependency Change?

None

### CODE REVIEW

**Comment by ronggegu** [comment]
resnet50_v1_5(onnx) test multi_instance failed  https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-windows/1328//consoleText

**Comment by chensuyue** [comment]
[extension test - 2.16](https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4376/artifact/report.html)

**Comment by Spycsh** [comment]
[#4401](https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4401) for debug

**Comment by Spycsh** [comment]
[#4402](https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4402) for debug

**Comment by Spycsh** [comment]
[#4406](https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4406/) for debug: why windows log is not dumped?

**Comment by Spycsh** [comment]
This commit fix following problems:

* Windows multi-instance benchmark do not dump log
* Windows multi-instance benchmark do not summary benchmark (Average Latency & Overall throughput)
* Multiple Windows multi-instance commands cannot be executed at once, but should be executed command by command

**Comment by Spycsh** [comment]
[4416](https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4416/) for test

**Comment by Spycsh** [comment]
[#4429](https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4429/) for test

**Comment by Spycsh** [comment]
@chensuyue [#4429](https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4429/) passed. It seems that the results for benchmarking fp32 and int8 models are the same. It should not be issue on my side. Please check whether fp32 and int8 benchmark use the same model path.

**Review by chensuyue — APPROVED** [review]

**Pull request merged**
