### PR TITLE
improve ipex example benchmark

### PR DESCRIPTION
**Pull request by changwangss**
Signed-off-by: changwa1 <chang1.wang@intel.com>

## Type of Change

1. modify benchmark to compare ipex optimized torchscript mode int8 model v.s. ipex optimized torchscript mode fp32 model
2. remove invaild code about get example_input in int8 model load function

## Description

detail description 
JIRA ticket: xxx

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Comment by changwangss** [comment]
https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4099/

**Comment by changwangss** [comment]
https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4121/

**Comment by changwangss** [comment]
https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4128/

**Comment by changwangss** [comment]
bert_large/distilbert: https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4149/

**Review by PenghuiCheng — APPROVED** [review]

**Comment by changwangss** [comment]
https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4194/

**Comment by changwangss** [comment]
distilbert: https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/4195/artifact/report.html

**Pull request merged**
