### PR TITLE
[WOQ]support AutoRound

### PR DESCRIPTION
**Pull request by WeiweiZhang1**
## Type of Change

new feature

## Description

AutoRound provides an advanced weight-only quantization algorithm for broad models based on SignRound. It can achieve noticeable improvements, often significantly improvements than those of SignRound, at the cost of approximately 2.5 times the quantization runtime.

## CheckList

LLaMAV1 done
LLaMAv2 done
LaMini-GPT-124M done
QWEN1-8B done,but has random issue
OPT-125M done
Mistral-7b Smoke test done
Bloom-560 smoke test done
falcon-7b smoke test done
gpt-leo-125m smoke test done
stablelm-base-alpha-3b smoke test done
dolly-v2-3b smoke test done
mpt-7b smoke test done
gpt-j-6b smoke test done
chatglm2-6b smoke test done

### CODE REVIEW

**Comment by chensuyue** [comment]
> ## Type of Change
> feature or bug fix or documentation or validation or others API changed or not
> 
> ## Description
> detail description
> 
> ## Expected Behavior & Potential Risk
> the expected behavior that triggered by this PR
> 
> ## How has this PR been tested?
> how to reproduce the test (including hardware information)
> 
> ## Dependency Change?
> any library dependency introduced or removed

Please update the descriptions.

**Comment by wenhuach21** [comment]
Falcon 7b bug  File "/home/wenhuach/neural-compressor-bk/neural_compressor/adaptor/torch_utils/autoround/autoround.py", line 693, in block_forward
    alibi = alibi.reshape(-1, alibi.shape[2], alibi.shape[3])
AttributeError: 'NoneType' object has no attribute 'reshape'
 @WeiweiZhang1

**Comment by wenhuach21** [comment]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:12<00:00,  1.57s/it]
Traceback (most recent call last):
  File "/home/wenhuach/neural-compressor/examples/pytorch/nlp/huggingface_models/language-modeling/quantization/autoround/main.py", line 190, in <module>
    tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
  File "/home/wenhuach/anaconda3/envs/optround/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 738, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/wenhuach/anaconda3/envs/optround/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2017, in from_pretrained
    return cls._from_pretrained(
  File "/home/wenhuach/anaconda3/envs/optround/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2249, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/wenhuach/.cache/huggingface/modules/transformers_modules/chatglm-6b/tokenization_chatglm.py", line 196, in __init__
    super().__init__(
  File "/home/wenhuach/anaconda3/envs/optround/lib/python3.9/site-packages/transformers/tokenization_utils.py", line 367, in __init__
    self._add_tokens(
  File "/home/wenhuach/anaconda3/envs/optround/lib/python3.9/site-packages/transformers/tokenization_utils.py", line 467, in _add_tokens
    current_vocab = self.get_vocab().copy()
  File "/home/wenhuach/.cache/huggingface/modules/transformers_modules/chatglm-6b/tokenization_chatglm.py", line 248, in get_vocab
    vocab = {self._convert_id_to_token(i): i for i in range(self.vocab_size)}
  File "/home/wenhuach/.cache/huggingface/modules/transformers_modules/chatglm-6b/tokenization_chatglm.py", line 244, in vocab_size
    return self.sp_tokenizer.num_tokens
AttributeError: 'ChatGLMTokenizer' object has no attribute 'sp_tokenizer'
@WeiweiZhang1

**Review by xin3he — APPROVED** [review]

**Comment by WeiweiZhang1** [comment]
> Falcon 7b bug File "/home/wenhuach/neural-compressor-bk/neural_compressor/adaptor/torch_utils/autoround/autoround.py", line 693, in block_forward alibi = alibi.reshape(-1, alibi.shape[2], alibi.shape[3]) AttributeError: 'NoneType' object has no attribute 'reshape' @WeiweiZhang1

fixed

**Pull request merged**
