### PR TITLE
Integrate AutoRound v0.4 [3x]

### PR DESCRIPTION
**Pull request by Kaihui-intel**
## Type of Change

feature or bug fix or documentation or validation or others  
API changed or not

## Description

- quant_block_list -> to_quant_block_names
- MLLM API

opt-125m
hf (), gen_kwargs: (None), limit: None, num_fewshot: None, batch_size: 8

|    Tasks     |Version|Filter|n-shot|  Metric  |   | Value |   |Stderr|
|--------------|------:|------|-----:|----------|---|------:|---|-----:|
|lambada_openai|      1|none  |     0|acc       |↑  | 0.3707|±  |0.0067|
|              |       |none  |     0|perplexity|↓  |27.7836|±  |1.0242|

Accuracy: 0.37066
Batch size = 8

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Comment by yiliu30** [comment]
@Kaihui-intel Please avoid mixing code for 2.x and 3.x in a single PR.

**Comment by yiliu30** [comment]
@Kaihui-intel Please trigger some extension tests as well.

**Comment by Kaihui-intel** [comment]
> @Kaihui-intel Please trigger some extension tests as well.

Update the test data in the description. A separate PR will be raised for the MLLM examples (structure and extension tests).

**Comment by Kaihui-intel** [comment]
@XuehaoSun baseline failed as [trl-internal-testing/tiny-random-OPTForCausalLM](https://huggingface.co/trl-internal-testing/tiny-random-OPTForCausalLM) 404 not found.
In this PR, we are using [trl-internal-testing/tiny-OPTForCausalLM](https://huggingface.co/trl-internal-testing/tiny-OPTForCausalLM) as a replacement.

**Review by yiliu30 — APPROVED** [review]

**Review by WeiweiZhang1 — APPROVED** [review]

**Pull request merged**
